---
language: python
sudo: required
warnings_are_errors: true
python:
    - 2.7

install:
    - pip install -r requirements.devel.txt
    - pip install coveralls

script:
    #- python setup.py lint
    - python setup.py test
    - coverage run --source=urlchecker setup.py test
after_success:
    coveralls
